# Generated by Django 3.0.6 on 2020-12-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='bysj',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='csrq',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='dzrq',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lxsj',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='sysj',
            field=models.CharField(max_length=32),
        ),
    ]
