# Generated by Django 3.0.6 on 2020-12-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20201225_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dy',
            old_name='rdsjAndJSR',
            new_name='jsr',
        ),
        migrations.AddField(
            model_name='dy',
            name='rds',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
