# Generated by Django 3.0.6 on 2020-12-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20201228_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dy',
            old_name='rds',
            new_name='rdsj',
        ),
    ]
