# Generated by Django 3.0.6 on 2020-12-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20201228_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hxxm',
            old_name='dfdwmc',
            new_name='brwc',
        ),
        migrations.RenameField(
            model_name='hxxm',
            old_name='dfdz',
            new_name='dwmc',
        ),
        migrations.RenameField(
            model_name='hxxm',
            old_name='dflxrxm',
            new_name='dz',
        ),
        migrations.AddField(
            model_name='hxxm',
            name='lxrxm',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hxxm',
            name='xmzt',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lw',
            name='txzz',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
