# Generated by Django 3.0.6 on 2020-12-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20201228_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='hjqk',
            name='bz',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
